In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('combustion.csv',index_col=0)

In [3]:
df.head()

,fuel,Pc,eps,Cstar,MR,PcOvPe,subar,Tc,Tt,Te,Isp,gamma
0,C2H5OH,17.0,1.000879,1098.809268,0.75,1.678184,3,1085.460377,1030.853078,1027.691435,138.243787,1.136492
1,C2H5OH,17.0,1.000879,1098.809268,0.75,1.678184,2,1085.460377,1030.853078,1027.691435,138.243787,1.136492
2,C2H5OH,17.0,1.001026,1139.399724,1.00,1.678184,3,1140.034568,1079.768411,1076.053771,143.508297,1.144131
3,C2H5OH,17.0,1.001026,1139.399724,1.00,1.678184,2,1140.034568,1079.768411,1076.053771,143.508297,1.144131
4,C2H5OH,17.0,1.001190,1169.981222,1.25,1.678184,3,1197.565234,1122.574428,1118.111379,147.739013,1.155159

In [5]:
df.sort_values(['Pc','Tc'],ascending=[False,False])

,fuel,Pc,eps,Cstar,MR,PcOvPe,subar,Tc,Tt,Te,Isp,gamma
8002,propane,39.5,1.312063,1635.167325,7.75,3.899309,3,3324.032788,3117.159711,2820.809326,224.272690,1.171044
8003,propane,39.5,1.312063,1635.167325,7.75,3.899309,2,3324.032788,3117.159711,2820.809326,224.272690,1.171044
5334,methane,39.5,1.302822,1690.505177,7.75,3.899309,3,3318.195609,3094.693668,2771.201243,231.521620,1.189124
5335,methane,39.5,1.302822,1690.505177,7.75,3.899309,2,3318.195609,3094.693668,2771.201243,231.521620,1.189124
8000,propane,39.5,1.307688,1636.753936,7.50,3.899309,3,3312.307002,3098.856384,2790.162578,224.323708,1.180165
...,...,...,...,...,...,...,...,...,...,...,...,...
3,C2H5OH,17.0,1.001026,1139.399724,1.00,1.678184,2,1140.034568,1079.768411,1076.053771,143.508297,1.144131
0,C2H5OH,17.0,1.000879,1098.809268,0.75,1.678184,3,1085.460377,1030.853078,1027.691435,138.243787,1.136492
1,C2H5OH,17.0,1.000879,1098.809268,0.75,1.678184,2,1085.460377,1030.853078,1027.691435,138.243787,1.136492
5336,propane,17.0,1.001038,1118.939826,0.75,1.678184,3,1082.564526,1021.715798,1017.895432,140.911158,1.144668
5337,propane,17.0,1.001038,1118.939826,0.75,1.678184,2,1082.564526,1021.715798,1017.895432,140.911158,1.144668