In [14]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv('combustion.csv',index_col=0)

In [16]:
df.head()

,fuel,Pc,eps,Cstar,MR,PcOvPe,subar,Tc,Tt,Te,Isp,gamma
0,C2H5OH,5.0,NaN,1081.392931,0.75,0.493583,3,1016.608090,968.423233,1085.709140,0.0,0.0
1,C2H5OH,5.0,NaN,1081.392931,0.75,0.493583,2,1016.608090,968.423233,1085.709140,0.0,0.0
2,C2H5OH,5.0,NaN,1119.711031,1.00,0.493583,3,1067.121676,1014.082685,1145.993277,0.0,0.0
3,C2H5OH,5.0,NaN,1119.711031,1.00,0.493583,2,1067.121676,1014.082685,1145.993277,0.0,0.0
4,C2H5OH,5.0,NaN,1149.142280,1.25,0.493583,3,1121.118980,1054.862634,1242.378976,0.0,0.0

In [17]:
df.sort_values(['Pc','Tc'],ascending=[False,False])

,fuel,Pc,eps,Cstar,MR,PcOvPe,subar,Tc,Tt,Te,Isp,gamma
12178,propane,39.5,1.312063,1635.167325,7.75,3.899309,3,3324.032788,3117.159711,2820.809326,224.272690,1.171044
12179,propane,39.5,1.312063,1635.167325,7.75,3.899309,2,3324.032788,3117.159711,2820.809326,224.272690,1.171044
8118,methane,39.5,1.302822,1690.505177,7.75,3.899309,3,3318.195609,3094.693668,2771.201243,231.521620,1.189124
8119,methane,39.5,1.302822,1690.505177,7.75,3.899309,2,3318.195609,3094.693668,2771.201243,231.521620,1.189124
12176,propane,39.5,1.307688,1636.753936,7.50,3.899309,3,3312.307002,3098.856384,2790.162578,224.323708,1.180165
...,...,...,...,...,...,...,...,...,...,...,...,...
3,C2H5OH,5.0,NaN,1119.711031,1.00,0.493583,2,1067.121676,1014.082685,1145.993277,0.000000,0.000000
0,C2H5OH,5.0,NaN,1081.392931,0.75,0.493583,3,1016.608090,968.423233,1085.709140,0.000000,0.000000
1,C2H5OH,5.0,NaN,1081.392931,0.75,0.493583,2,1016.608090,968.423233,1085.709140,0.000000,0.000000
8120,propane,5.0,NaN,1103.169181,0.75,0.493583,3,1010.175797,955.713778,1088.395826,0.000000,0.000000
8121,propane,5.0,NaN,1103.169181,0.75,0.493583,2,1010.175797,955.713778,1088.395826,0.000000,0.000000

In [20]:
combustion_sorted = df.sort_values(['Pc','Tc'],ascending=[False,False])
combustion_sorted.to_csv('combustion_sorted.csv', index=False)